version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    networks:
      zk-network:
        ipv4_address: 10.1.1.41
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: "yes"

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    networks:
      zk-network:
        ipv4_address: 10.1.1.42
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: "yes"

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    networks:
      zk-network:
        ipv4_address: 10.1.1.43
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: "yes"

  zoo-monkey:
    build: .
    restart: always
    networks:
      zk-network:
        ipv4_address: 10.1.1.44
    environment:
      ZOO_NODE: zoo1:2181
networks:
  zk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24