apiVersion: v1
kind: ReplicationController
metadata:
  name: network-exp-server
spec:
  replicas: 1
  selector:
    app: network-exp-server
  template:
    metadata:
      name: network-exp-server
      labels:
        app: network-exp-server
    spec:
      containers:
      - name: network-exp-server
        env:
          - name: PORT
            value: "6000"
        image: sushshring/network-exp:server
        imagePullPolicy: Always
        ports:
          - containerPort: 6000
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: network-exp-server
#spec:
#  ports:
#  - port: 6000
#    targetPort: 6000
#  selector:
#    app: network-exp-server
#  type: LoadBalancer
#---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: 'network-exp-server'
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000
---

